---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  MATRIX: >-
    [
      {"MYSQL_SERVER": "mysql-5.5"},
      {"MYSQL_SERVER": "mysql-5.6"},
      {"MYSQL_SERVER": "mysql-5.7"},
      {"MYSQL_SERVER": "mysql-8.0"},
      {"MYSQL_SERVER": "percona-5.5"},
      {"MYSQL_SERVER": "percona-5.6"},
      {"MYSQL_SERVER": "percona-5.7"},
      {"MYSQL_SERVER": "percona-8.0"},
      {"MYSQL_SERVER": "mariadb-5.5"},
      {"MYSQL_SERVER": "mariadb-10.0"},
      {"MYSQL_SERVER": "mariadb-10.1"},
      {"MYSQL_SERVER": "mariadb-10.2"},
      {"MYSQL_SERVER": "mariadb-10.3"},
      {"MYSQL_SERVER": "mariadb-10.4"},
      {"MYSQL_SERVER": "mariadb-10.5"},
      {"MYSQL_SERVER": "mariadb-10.6"},
      {"MYSQL_SERVER": "mariadb-10.7"},
      {"MYSQL_SERVER": "mariadb-10.8"},

      {"PGSQL_SERVER": "PgSQL 9.0"},
      {"PGSQL_SERVER": "PgSQL 9.1"},
      {"PGSQL_SERVER": "PgSQL 9.2"},
      {"PGSQL_SERVER": "PgSQL 9.2-alpine"},
      {"PGSQL_SERVER": "PgSQL 9.3"},
      {"PGSQL_SERVER": "PgSQL 9.3-alpine"},
      {"PGSQL_SERVER": "PgSQL 9.4"},
      {"PGSQL_SERVER": "PgSQL 9.4-alpine"},
      {"PGSQL_SERVER": "PgSQL 9.5"},
      {"PGSQL_SERVER": "PgSQL 9.5-alpine"},
      {"PGSQL_SERVER": "PgSQL 9.6"},
      {"PGSQL_SERVER": "PgSQL 9.6-alpine"},
      {"PGSQL_SERVER": "PgSQL 10"},
      {"PGSQL_SERVER": "PgSQL 10-alpine"},
      {"PGSQL_SERVER": "PgSQL 11"},
      {"PGSQL_SERVER": "PgSQL 11-alpine"},
      {"PGSQL_SERVER": "PgSQL 12"},
      {"PGSQL_SERVER": "PgSQL 12-alpine"},
      {"PGSQL_SERVER": "PgSQL 13"},
      {"PGSQL_SERVER": "PgSQL 13-alpine"},
      {"PGSQL_SERVER": "PgSQL 14"},
      {"PGSQL_SERVER": "PgSQL 14-alpine"},
      {"PGSQL_SERVER": "PgSQL latest"},
      {"PGSQL_SERVER": "PgSQL alpine"},

      {"REDIS_SERVER": "Redis 2.8"},
      {"REDIS_SERVER": "Redis 3.0"},
      {"REDIS_SERVER": "Redis 3.0-alpine"},
      {"REDIS_SERVER": "Redis 3.2"},
      {"REDIS_SERVER": "Redis 3.2-alpine"},
      {"REDIS_SERVER": "Redis 4.0"},
      {"REDIS_SERVER": "Redis 4.0-alpine"},
      {"REDIS_SERVER": "Redis 5.0"},
      {"REDIS_SERVER": "Redis 5.0-alpine"},
      {"REDIS_SERVER": "Redis 6.0"},
      {"REDIS_SERVER": "Redis 6.0-alpine"},
      {"REDIS_SERVER": "Redis 6.2"},
      {"REDIS_SERVER": "Redis 6.2-alpine"},
      {"REDIS_SERVER": "Redis latest"},
      {"REDIS_SERVER": "Redis alpine"},

      {"MEMCD_SERVER": "Memcd 1.4"},
      {"MEMCD_SERVER": "Memcd 1.4-alpine"},
      {"MEMCD_SERVER": "Memcd 1.5"},
      {"MEMCD_SERVER": "Memcd 1.5-alpine"},
      {"MEMCD_SERVER": "Memcd 1.6"},
      {"MEMCD_SERVER": "Memcd 1.6-alpine"},
      {"MEMCD_SERVER": "Memcd latest"},
      {"MEMCD_SERVER": "Memcd alpine"},

      {"MONGO_SERVER": "Mongo 2.8"},
      {"MONGO_SERVER": "Mongo 3.0"},
      {"MONGO_SERVER": "Mongo 3.2"},
      {"MONGO_SERVER": "Mongo 3.4"},
      {"MONGO_SERVER": "Mongo 3.6"},
      {"MONGO_SERVER": "Mongo 4.0"},
      {"MONGO_SERVER": "Mongo 4.2"},
      {"MONGO_SERVER": "Mongo 4.4"},
      {"MONGO_SERVER": "Mongo 5.0"},
      {"MONGO_SERVER": "Mongo latest"}
    ]


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      matrix:
        description: "The determined version matrix"
        value: ${{ jobs.params.outputs.matrix }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: "[Set-Output] Matrix"
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$( echo '${{ env.MATRIX }}' | jq -M -c )"

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Matrix'
          echo '--------------------'
          echo '${{ steps.set-matrix.outputs.matrix }}'
          echo
