---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Memcd


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+*'


jobs:
  # -----------------------------------------------------------------------------------------------
  # (1/3) Determine parameter settings
  # -----------------------------------------------------------------------------------------------
  params:
    uses: ./.github/workflows/params-version-memcd.yml


  # -----------------------------------------------------------------------------------------------
  # (2/3) Test with default settings
  # -----------------------------------------------------------------------------------------------
  default:
    needs: [params]
    uses: ./.github/workflows/zzz-reuse-tests.yml
    with:
      matrix: ${{ needs.params.outputs.matrix }}
      custom_config: false
      operating_system: ubuntu-latest


  # -----------------------------------------------------------------------------------------------
  # (3/3) Test with customizedt settings
  # -----------------------------------------------------------------------------------------------
  custom:
    needs: [params]
    uses: ./.github/workflows/zzz-reuse-tests.yml
    with:
      matrix: ${{ needs.params.outputs.matrix }}
      custom_config: true
      operating_system: ubuntu-latest
