---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Versions


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+*'


jobs:
  # -----------------------------------------------------------------------------------------------
  # (1/2) Determine parameter settings
  # -----------------------------------------------------------------------------------------------
  params:
    uses: ./.github/workflows/params-versions.yml


  # -----------------------------------------------------------------------------------------------
  # (2/2) Configure Build and Deploy Matrices
  # -----------------------------------------------------------------------------------------------
  test:
    needs: [params]
    uses: ./.github/workflows/zzz-reuse-tests.yml
    with:
      matrix: ${{ needs.params.outputs.matrix }}
      custom_config: false
